"""Text-level analysis of the transcript: summary, tone, and AI-voice/text signals."""

from __future__ import annotations

import re
from dataclasses import dataclass, field


@dataclass
class TextSignals:
    summary: str
    keywords: list[str]
    tone: str
    tts_risk: int  # 0..100 — AI-generated / synthetic-voice suspicion from text+pacing cues
    clickbait_risk: int  # 0..100
    claim_risk: int  # 0..100 — sensational/absolute claims
    self_disclosure_risk: int = 0  # 0..100 — title/description explicitly says AI/parody/synthetic
    self_disclosure_evidence: list[str] = field(default_factory=list)
    facts: list[str] = field(default_factory=list)
    risk: float = field(init=False)

    def __post_init__(self) -> None:
        # Single source of truth for the text-level weighted risk score. This
        # used to be a @property, which dataclasses.asdict() silently drops —
        # so report.py was recomputing the same weights from scratch in a
        # second place, and this property was effectively dead code. Now it's
        # a real field, so report.py reads it directly.
        self.risk = round(
            self.tts_risk * 0.35
            + self.clickbait_risk * 0.15
            + self.claim_risk * 0.10
            + self.self_disclosure_risk * 0.40,
            1,
        )


# Signals that often accompany synthetic/AI voices or scripted AI content.
_TTS_REPEAT_RE = re.compile(r"\b(\w+)( \1){2,}\b", re.IGNORECASE)
_TTS_FILLER_RE = re.compile(r"\b(um|uh|ah|er)\b", re.IGNORECASE)
_TTS_PUNCT_RE = re.compile(r"[…]|\.\.\.|\. \.")

_CLICKBAIT_WORDS = [
    "충격", "충격적", "경악", "정체", "전격", "드디어", "대박", "이럴 수가", "믿어지지", "절대", "무조건",
    "shocking", "bomb", "unbelievable", "secret", "exposed", "crazy", "insane", "you won't",
]
_CLAIM_WORDS = [
    "반드시", "무조건", "확실히", "100%", "절대", "전부 다", "알려지지 않은", "숨겨진", "비밀",
    "무조건", "한국인", "국민", "시청자 여러분", "must", "always", "never", "everyone",
]
_HYPE_PUNCT = re.compile(r"[!！?？]{2,}")


def summarize(text: str, max_sentences: int = 3, max_len: int = 300) -> str:
    """Extractive summary: pick top sentences by keyword frequency within the first chunk."""
    if not text:
        return "(음성 텍스트 없음)"
    sentences = re.split(r"(?<=[.!?。！？])\s+", text)
    sentences = [s.strip() for s in sentences if len(s.strip()) > 8]
    if not sentences:
        return text[:max_len]
    if len(sentences) <= max_sentences:
        return " ".join(sentences)[:max_len]

    from collections import Counter
    stop = set("the a an and or of to in is are was were 이 가 은 는 이고 하는 그리고".split())
    words = [w.lower() for w in re.findall(r"[A-Za-z가-힣]+", text) if w.lower() not in stop]
    freq = Counter(words)

    def score(s: str) -> float:
        return sum(freq.get(w.lower(), 0) for w in re.findall(r"[A-Za-z가-힣]+", s))

    ranked = sorted(sentences, key=score, reverse=True)[:max_sentences]
    out = []
    for s in sentences:
        if s in ranked and s not in out:
            out.append(s)
        if len(out) >= max_sentences:
            break
    return " ".join(out)[:max_len]


# Phrases an uploader/creator uses to disclose that a video is AI-made/parody —
# the cheapest, most reliable signal we have (Tier 0 in the project plan): if
# the title already says "AI로 제작된 패러디 영상", we don't need a classifier.
_SELF_DISCLOSURE_PATTERNS = [
    "ai로 제작", "ai가 만든", "ai 생성", "ai로 만든", "인공지능으로 제작", "인공지능이 만든",
    "가상의 영상", "가상 인물", "합성 영상", "딥페이크", "패러디 영상", "패러디",
    "deepfake", "generated by ai", "ai-generated", "ai generated", "synthetic media",
    "made with ai", "created using ai", "실제가 아닙니다", "실제 상황이 아닙니다",
]


def detect_self_disclosure(title: str | None, description: str | None) -> tuple[int, list[str]]:
    """Scan the video's own title/description for explicit AI/parody/synthetic labels."""
    haystack = f"{title or ''} {description or ''}".lower()
    hits = [p for p in _SELF_DISCLOSURE_PATTERNS if p in haystack]
    if not hits:
        return 0, []
    score = min(100, 55 + len(hits) * 15)
    evidence = [f'제목/설명에 자가표기 발견: "{h}"' for h in hits]
    return score, evidence


def analyze(text: str, language: str | None = None, title: str | None = None,
            description: str | None = None) -> TextSignals:
    self_disclosure_risk, self_disclosure_evidence = detect_self_disclosure(title, description)

    if not text:
        facts = [f"자가표기: {'; '.join(self_disclosure_evidence)}"] if self_disclosure_evidence else []
        return TextSignals(
            summary="(음성 텍스트 없음)", keywords=[], tone="unknown",
            tts_risk=0, clickbait_risk=0, claim_risk=0,
            self_disclosure_risk=self_disclosure_risk,
            self_disclosure_evidence=self_disclosure_evidence,
            facts=facts,
        )

    lowered = text.lower()
    word_count = len(text.split())
    avg_seg_len = word_count / max(len(re.split(r"(?<=[.!?。！？])\s+", text)), 1)

    # TTS / synthetic voice cues
    repeats = _TTS_REPEAT_RE.findall(text)
    fillers = _TTS_FILLER_RE.findall(text)
    ellipsis = len(_TTS_PUNCT_RE.findall(text))
    monotone_len = avg_seg_len > 55  # unusually long run-on = scripted/read-off
    tts_penalty = len(repeats) * 8 + len(fillers) * 3 + ellipsis * 4
    if monotone_len:
        tts_penalty += 12
    tts_risk = min(100, tts_penalty)

    # Clickbait
    cb_hits = sum(lowered.count(w.lower()) for w in _CLICKBAIT_WORDS)
    hype = max(1, len(_HYPE_PUNCT.findall(text)))
    clickbait_risk = min(100, cb_hits * 9 + hype * 6)

    # Absolute / sensational claims
    claim_hits = sum(lowered.count(w.lower()) for w in _CLAIM_WORDS)
    claim_risk = min(100, claim_hits * 12)

    tone = _tone(text)
    keywords = _keywords(text)

    facts: list[str] = []
    if language:
        facts.append(f"언어: {language}")
    facts.append(f"단어수: {word_count}")

    return TextSignals(
        summary=summarize(text),
        keywords=keywords,
        tone=tone,
        tts_risk=tts_risk,
        clickbait_risk=clickbait_risk,
        claim_risk=claim_risk,
        self_disclosure_risk=self_disclosure_risk,
        self_disclosure_evidence=self_disclosure_evidence,
        facts=facts,
    )


def _keywords(text: str, top: int = 5) -> list[str]:
    from collections import Counter
    stop = set("의 가 이 은 는 에 를 하고 그리고 하지만 그 이 그게 너무 정말 아 . , ! ?".split())
    words = [w for w in re.findall(r"[A-Za-z가-힣]{2,}", text) if w.lower() not in stop]
    return [w for w, _ in Counter(words).most_common(top)]


def _tone(text: str) -> str:
    pos = sum(text.count(w) for w in ["감사", "좋", "행복", "멋", "최고", "great", "good", "love", "awesome"])
    neg = sum(text.count(w) for w in ["불안", "위험", "나쁘", "문제", "사고", "무섭", "bad", "danger", "scary", "hate"])
    shout = len(_HYPE_PUNCT.findall(text))
    if neg > pos:
        return "부정/경고"
    if pos > neg:
        return "긍정/홍보"
    if shout:
        return "선동/흥분"
    return "중립"
